global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-url-shortener'
    metrics_path: '/metrics' # O endpoint padr√£o do prometheus-flask-exporter
    static_configs:
    - targets: ['host.docker.internal:5000'] # Aponta para a porta 5000